-- 런처 앱 목록 (공개 정보만). 미연결 항목은 주소를 넣지 않음.
INSERT INTO app_registry (app_id, name_ko, name_uz, name_ru, url, kind, required_group, status, sort, health_url) VALUES
 ('nongjajae',         '농자재 유통 시스템',       'Agro materiallar tizimi',          'Система агроматериалов',            'https://firmmit-nongjajae.global-630.workers.dev', 'staff_app',     'NONGJAJAE',    'active',        10,  'https://firmmit-nongjajae.global-630.workers.dev'),
 ('quote-backoffice',  '견적 백오피스',            'Smeta boshqaruvi',                 'Бэк-офис смет',                     'https://firmmit-quote.pages.dev/backoffice',       'staff_app',     'CONSTRUCTION', 'active',        20,  NULL),
 ('icheon-vfarm',      '이천 수직농장 대시보드',   'Vertikal ferma paneli (Icheon)',   'Панель вертикальной фермы (Ичхон)', 'https://firmmit2000.global-630.workers.dev',        'staff_app',     'RND',          'active',        30,  'https://firmmit2000.global-630.workers.dev'),
 ('amim',              'AMIM',                     'AMIM',                             'AMIM',                              'https://firmmit-amim.vercel.app',                  'staff_app',     'UZ',           'active',        40,  'https://firmmit-amim.vercel.app'),
 ('quote',             '하우스 견적',              'Issiqxona smetasi',                'Смета теплицы',                     'https://firmmit-quote.pages.dev',                  'public_site',   NULL,           'active',        110, 'https://firmmit-quote.pages.dev'),
 ('academy-apply',     '아카데미 지원',            'Akademiyaga ariza',                'Заявка в академию',                 'https://firmmit-apply.pages.dev',                  'public_site',   NULL,           'active',        120, 'https://firmmit-apply.pages.dev'),
 ('fino',              'FINO',                     'FINO',                             'FINO',                              'https://firmmit-fino.vercel.app',                  'public_site',   NULL,           'active',        130, 'https://firmmit-fino.vercel.app'),
 ('firmmit-mall',      '퍼밋몰',                   'FIRMMIT Mall',                     'FIRMMIT Mall',                      'https://firmmitmall.com',                          'public_site',   NULL,           'active',        140, 'https://firmmitmall.com'),
 ('homepage-kr',       '한국 홈페이지',            'Veb-sayt (Koreya)',                'Сайт (Корея)',                      'https://www.firmmit.kr',                           'public_site',   NULL,           'active',        150, 'https://www.firmmit.kr'),
 ('homepage-uz',       '우즈벡 홈페이지',          'Veb-sayt (Oʻzbekiston)',           'Сайт (Узбекистан)',                 'https://firmmit.uz',                               'public_site',   NULL,           'active',        160, 'https://firmmit.uz'),
 ('smartstore',        '스마트스토어',             'Onlayn doʻkon',                    'Интернет-магазин',                  NULL,                                               'public_site',   NULL,           'not_connected', 170, NULL),
 ('firmmit-fresh',     '퍼밋프레시',               'FIRMMIT Fresh',                    'FIRMMIT Fresh',                     NULL,                                               'public_site',   NULL,           'not_connected', 180, NULL),
 ('ahost',             'aHOST 호스팅 관리',        'aHOST hosting boshqaruvi',         'aHOST: управление хостингом',       'https://clients.ahost.uz',                         'admin_console', 'ADMIN',        'active',        210, NULL),
 ('band-slack-bridge', 'BAND→Slack 브리지',        'BAND→Slack koʻprigi',              'Мост BAND→Slack',                   NULL,                                               'admin_console', 'ADMIN',        'not_connected', 220, NULL),
 ('tapo-cctv',         'Tapo CCTV',                'Videokuzatuv (Tapo)',              'Видеонаблюдение (Tapo)',            NULL,                                               'admin_console', 'ADMIN',        'not_connected', 230, NULL),
 ('telegram',          '텔레그램 채널',            'Telegram kanali',                  'Telegram-канал',                    'https://t.me/firmmit_global',                      'channel',       NULL,           'active',        310, NULL),
 ('kakao-bot',         '카카오 봇',                'Kakao chat-bot',                   'Чат-бот Kakao',                     NULL,                                               'channel',       NULL,           'not_connected', 320, NULL);
